name: Build and Package Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install and build frontend
        run: |
          chmod +x ./package.sh
          ./package.sh
        env:
          CI: true

      # Archive the build for deployment
      - name: Archive build artifacts
        run: zip -r dudada.zip dist/*
        env:
          CI: true

      # Upload the artifact for download or further deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dudada
          path: dudada.zip
